### PR TITLE
Readme file

### PR DESCRIPTION
**Pull request by bsuma30**
Created and updated a Readme file for the Sticky notes app

### CODE REVIEW

**Comment by raghavtilak** [comment]
Hi @suma30 ,
It would be much better if there was a small working demo.
You can visit this [link](https://www.geeksforgeeks.org/how-to-build-a-sticky-notes-application-in-android-studio/) for better information. This repo was made as an example of this article.
I appreciate your time and work.

**Comment by bsuma30** [comment]
I have added the demo pics but it is not showing up in the readme file, could you please guide about this

**Comment by raghavtilak** [comment]
Sure. Try to add the direct link, instead of the relative path. Have a look at this [solution](https://stackoverflow.com/a/14494775/8735375).
Open the image from the demo folder, or just copy the link of that image and use that link, instead of this '/demo_pics/S1.png', for all images you want to add.
Let me know if the issue persists.

**Comment by bsuma30** [comment]
@raghavtilak 
Solved the issue, once could you check it please

**Comment by raghavtilak** [comment]
Great @suma30 . Good work.
Thanks for your time and work. 😄👍🏻

**Comment by bsuma30** [comment]
Thanks a lot!

**Pull request merged**
